//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.30 at 09:31:19 PM VLAT 
//


package ru.ptkom.ecsscallrecordsback.model.CallHistoryModel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorReasonType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="errorReasonType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="unknown_error"/>
 *     &lt;enumeration value="bad_token_info"/>
 *     &lt;enumeration value="set_error"/>
 *     &lt;enumeration value="exception"/>
 *     &lt;enumeration value="error"/>
 *     &lt;enumeration value="invalid_input_xml"/>
 *     &lt;enumeration value="nocommand"/>
 *     &lt;enumeration value="invalid_xml"/>
 *     &lt;enumeration value="bad_licence"/>
 *     &lt;enumeration value="profile_in_use"/>
 *     &lt;enumeration value="no_rights"/>
 *     &lt;enumeration value="parse_error"/>
 *     &lt;enumeration value="exit"/>
 *     &lt;enumeration value="canceled_by_user"/>
 *     &lt;enumeration value="not_exists"/>
 *     &lt;enumeration value="already_declared"/>
 *     &lt;enumeration value="restricted_name"/>
 *     &lt;enumeration value="domain_not_exists"/>
 *     &lt;enumeration value="domain_not_found"/>
 *     &lt;enumeration value="profile_not_exists"/>
 *     &lt;enumeration value="profile_not_found"/>
 *     &lt;enumeration value="ivr_restrictions_profile_not_exists"/>
 *     &lt;enumeration value="badflags"/>
 *     &lt;enumeration value="badargs"/>
 *     &lt;enumeration value="badinput"/>
 *     &lt;enumeration value="aborted"/>
 *     &lt;enumeration value="no_enough_addresses"/>
 *     &lt;enumeration value="no_enough_ifaces"/>
 *     &lt;enumeration value="invalid_range"/>
 *     &lt;enumeration value="const"/>
 *     &lt;enumeration value="db_error"/>
 *     &lt;enumeration value="invalid_value"/>
 *     &lt;enumeration value="invalid_queue_id"/>
 *     &lt;enumeration value="name_already_in_use"/>
 *     &lt;enumeration value="no_such_gateway"/>
 *     &lt;enumeration value="bad_gateway_type"/>
 *     &lt;enumeration value="no_signaling_gateway"/>
 *     &lt;enumeration value="no_trunk_gateway"/>
 *     &lt;enumeration value="no_such_opc"/>
 *     &lt;enumeration value="no_such_dpc"/>
 *     &lt;enumeration value="not_equal_dpc"/>
 *     &lt;enumeration value="bad_internal_iface_format"/>
 *     &lt;enumeration value="interface_already_exists"/>
 *     &lt;enumeration value="port_already_in_use"/>
 *     &lt;enumeration value="no_such_port"/>
 *     &lt;enumeration value="session_not_found"/>
 *     &lt;enumeration value="lock_not_found"/>
 *     &lt;enumeration value="already_blocked"/>
 *     &lt;enumeration value="bad_user_server_type"/>
 *     &lt;enumeration value="already_exists"/>
 *     &lt;enumeration value="cannot_get_data"/>
 *     &lt;enumeration value="no_such_user"/>
 *     &lt;enumeration value="connection_trouble"/>
 *     &lt;enumeration value="name_is_busy"/>
 *     &lt;enumeration value="context_not_found"/>
 *     &lt;enumeration value="alias_declaration_error"/>
 *     &lt;enumeration value="context_validation_error"/>
 *     &lt;enumeration value="invalid_user_name"/>
 *     &lt;enumeration value="invalid_alias_digits"/>
 *     &lt;enumeration value="invalid_address_format"/>
 *     &lt;enumeration value="invalid_routing_context"/>
 *     &lt;enumeration value="no_such_group"/>
 *     &lt;enumeration value="not_exists_agents"/>
 *     &lt;enumeration value="zone_used_in_resource"/>
 *     &lt;enumeration value="zone_not_found"/>
 *     &lt;enumeration value="site_used_in_resource"/>
 *     &lt;enumeration value="site_not_found"/>
 *     &lt;enumeration value="bad_node"/>
 *     &lt;enumeration value="undefined_properties"/>
 *     &lt;enumeration value="ivr_scripts_domain_limit"/>
 *     &lt;enumeration value="ivr_script_restricted_blocks"/>
 *     &lt;enumeration value="ivr_script_too_many_blocks"/>
 *     &lt;enumeration value="ivr_script_bad_first_block"/>
 *     &lt;enumeration value="ivr_script_bad_pass"/>
 *     &lt;enumeration value="already_defined"/>
 *     &lt;enumeration value="connection_failed"/>
 *     &lt;enumeration value="bad_id"/>
 *     &lt;enumeration value="src_bridge_not_exists"/>
 *     &lt;enumeration value="src_bridge_domain_not_exists"/>
 *     &lt;enumeration value="dst_bridge_already_exists"/>
 *     &lt;enumeration value="without_value"/>
 *     &lt;enumeration value="domain_limit"/>
 *     &lt;enumeration value="licence_limit"/>
 *     &lt;enumeration value="undefined_id"/>
 *     &lt;enumeration value="change_predefined"/>
 *     &lt;enumeration value="reason_in_use"/>
 *     &lt;enumeration value="status_in_use"/>
 *     &lt;enumeration value="set_in_use"/>
 *     &lt;enumeration value="set_not_exists"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "errorReasonType")
@XmlEnum
public enum ErrorReasonType {

    @XmlEnumValue("unknown_error")
    UNKNOWN_ERROR("unknown_error"),
    @XmlEnumValue("bad_token_info")
    BAD_TOKEN_INFO("bad_token_info"),
    @XmlEnumValue("set_error")
    SET_ERROR("set_error"),
    @XmlEnumValue("exception")
    EXCEPTION("exception"),
    @XmlEnumValue("error")
    ERROR("error"),
    @XmlEnumValue("invalid_input_xml")
    INVALID_INPUT_XML("invalid_input_xml"),
    @XmlEnumValue("nocommand")
    NOCOMMAND("nocommand"),
    @XmlEnumValue("invalid_xml")
    INVALID_XML("invalid_xml"),
    @XmlEnumValue("bad_licence")
    BAD_LICENCE("bad_licence"),
    @XmlEnumValue("profile_in_use")
    PROFILE_IN_USE("profile_in_use"),
    @XmlEnumValue("no_rights")
    NO_RIGHTS("no_rights"),
    @XmlEnumValue("parse_error")
    PARSE_ERROR("parse_error"),
    @XmlEnumValue("exit")
    EXIT("exit"),
    @XmlEnumValue("canceled_by_user")
    CANCELED_BY_USER("canceled_by_user"),
    @XmlEnumValue("not_exists")
    NOT_EXISTS("not_exists"),
    @XmlEnumValue("already_declared")
    ALREADY_DECLARED("already_declared"),
    @XmlEnumValue("restricted_name")
    RESTRICTED_NAME("restricted_name"),
    @XmlEnumValue("domain_not_exists")
    DOMAIN_NOT_EXISTS("domain_not_exists"),
    @XmlEnumValue("domain_not_found")
    DOMAIN_NOT_FOUND("domain_not_found"),
    @XmlEnumValue("profile_not_exists")
    PROFILE_NOT_EXISTS("profile_not_exists"),
    @XmlEnumValue("profile_not_found")
    PROFILE_NOT_FOUND("profile_not_found"),
    @XmlEnumValue("ivr_restrictions_profile_not_exists")
    IVR_RESTRICTIONS_PROFILE_NOT_EXISTS("ivr_restrictions_profile_not_exists"),
    @XmlEnumValue("badflags")
    BADFLAGS("badflags"),
    @XmlEnumValue("badargs")
    BADARGS("badargs"),
    @XmlEnumValue("badinput")
    BADINPUT("badinput"),
    @XmlEnumValue("aborted")
    ABORTED("aborted"),
    @XmlEnumValue("no_enough_addresses")
    NO_ENOUGH_ADDRESSES("no_enough_addresses"),
    @XmlEnumValue("no_enough_ifaces")
    NO_ENOUGH_IFACES("no_enough_ifaces"),
    @XmlEnumValue("invalid_range")
    INVALID_RANGE("invalid_range"),
    @XmlEnumValue("const")
    CONST("const"),
    @XmlEnumValue("db_error")
    DB_ERROR("db_error"),
    @XmlEnumValue("invalid_value")
    INVALID_VALUE("invalid_value"),
    @XmlEnumValue("invalid_queue_id")
    INVALID_QUEUE_ID("invalid_queue_id"),
    @XmlEnumValue("name_already_in_use")
    NAME_ALREADY_IN_USE("name_already_in_use"),
    @XmlEnumValue("no_such_gateway")
    NO_SUCH_GATEWAY("no_such_gateway"),
    @XmlEnumValue("bad_gateway_type")
    BAD_GATEWAY_TYPE("bad_gateway_type"),
    @XmlEnumValue("no_signaling_gateway")
    NO_SIGNALING_GATEWAY("no_signaling_gateway"),
    @XmlEnumValue("no_trunk_gateway")
    NO_TRUNK_GATEWAY("no_trunk_gateway"),
    @XmlEnumValue("no_such_opc")
    NO_SUCH_OPC("no_such_opc"),
    @XmlEnumValue("no_such_dpc")
    NO_SUCH_DPC("no_such_dpc"),
    @XmlEnumValue("not_equal_dpc")
    NOT_EQUAL_DPC("not_equal_dpc"),
    @XmlEnumValue("bad_internal_iface_format")
    BAD_INTERNAL_IFACE_FORMAT("bad_internal_iface_format"),
    @XmlEnumValue("interface_already_exists")
    INTERFACE_ALREADY_EXISTS("interface_already_exists"),
    @XmlEnumValue("port_already_in_use")
    PORT_ALREADY_IN_USE("port_already_in_use"),
    @XmlEnumValue("no_such_port")
    NO_SUCH_PORT("no_such_port"),
    @XmlEnumValue("session_not_found")
    SESSION_NOT_FOUND("session_not_found"),
    @XmlEnumValue("lock_not_found")
    LOCK_NOT_FOUND("lock_not_found"),
    @XmlEnumValue("already_blocked")
    ALREADY_BLOCKED("already_blocked"),
    @XmlEnumValue("bad_user_server_type")
    BAD_USER_SERVER_TYPE("bad_user_server_type"),
    @XmlEnumValue("already_exists")
    ALREADY_EXISTS("already_exists"),
    @XmlEnumValue("cannot_get_data")
    CANNOT_GET_DATA("cannot_get_data"),
    @XmlEnumValue("no_such_user")
    NO_SUCH_USER("no_such_user"),
    @XmlEnumValue("connection_trouble")
    CONNECTION_TROUBLE("connection_trouble"),
    @XmlEnumValue("name_is_busy")
    NAME_IS_BUSY("name_is_busy"),
    @XmlEnumValue("context_not_found")
    CONTEXT_NOT_FOUND("context_not_found"),
    @XmlEnumValue("alias_declaration_error")
    ALIAS_DECLARATION_ERROR("alias_declaration_error"),
    @XmlEnumValue("context_validation_error")
    CONTEXT_VALIDATION_ERROR("context_validation_error"),
    @XmlEnumValue("invalid_user_name")
    INVALID_USER_NAME("invalid_user_name"),
    @XmlEnumValue("invalid_alias_digits")
    INVALID_ALIAS_DIGITS("invalid_alias_digits"),
    @XmlEnumValue("invalid_address_format")
    INVALID_ADDRESS_FORMAT("invalid_address_format"),
    @XmlEnumValue("invalid_routing_context")
    INVALID_ROUTING_CONTEXT("invalid_routing_context"),
    @XmlEnumValue("no_such_group")
    NO_SUCH_GROUP("no_such_group"),
    @XmlEnumValue("not_exists_agents")
    NOT_EXISTS_AGENTS("not_exists_agents"),
    @XmlEnumValue("zone_used_in_resource")
    ZONE_USED_IN_RESOURCE("zone_used_in_resource"),
    @XmlEnumValue("zone_not_found")
    ZONE_NOT_FOUND("zone_not_found"),
    @XmlEnumValue("site_used_in_resource")
    SITE_USED_IN_RESOURCE("site_used_in_resource"),
    @XmlEnumValue("site_not_found")
    SITE_NOT_FOUND("site_not_found"),
    @XmlEnumValue("bad_node")
    BAD_NODE("bad_node"),
    @XmlEnumValue("undefined_properties")
    UNDEFINED_PROPERTIES("undefined_properties"),
    @XmlEnumValue("ivr_scripts_domain_limit")
    IVR_SCRIPTS_DOMAIN_LIMIT("ivr_scripts_domain_limit"),
    @XmlEnumValue("ivr_script_restricted_blocks")
    IVR_SCRIPT_RESTRICTED_BLOCKS("ivr_script_restricted_blocks"),
    @XmlEnumValue("ivr_script_too_many_blocks")
    IVR_SCRIPT_TOO_MANY_BLOCKS("ivr_script_too_many_blocks"),
    @XmlEnumValue("ivr_script_bad_first_block")
    IVR_SCRIPT_BAD_FIRST_BLOCK("ivr_script_bad_first_block"),
    @XmlEnumValue("ivr_script_bad_pass")
    IVR_SCRIPT_BAD_PASS("ivr_script_bad_pass"),
    @XmlEnumValue("already_defined")
    ALREADY_DEFINED("already_defined"),
    @XmlEnumValue("connection_failed")
    CONNECTION_FAILED("connection_failed"),
    @XmlEnumValue("bad_id")
    BAD_ID("bad_id"),
    @XmlEnumValue("src_bridge_not_exists")
    SRC_BRIDGE_NOT_EXISTS("src_bridge_not_exists"),
    @XmlEnumValue("src_bridge_domain_not_exists")
    SRC_BRIDGE_DOMAIN_NOT_EXISTS("src_bridge_domain_not_exists"),
    @XmlEnumValue("dst_bridge_already_exists")
    DST_BRIDGE_ALREADY_EXISTS("dst_bridge_already_exists"),
    @XmlEnumValue("without_value")
    WITHOUT_VALUE("without_value"),
    @XmlEnumValue("domain_limit")
    DOMAIN_LIMIT("domain_limit"),
    @XmlEnumValue("licence_limit")
    LICENCE_LIMIT("licence_limit"),
    @XmlEnumValue("undefined_id")
    UNDEFINED_ID("undefined_id"),
    @XmlEnumValue("change_predefined")
    CHANGE_PREDEFINED("change_predefined"),
    @XmlEnumValue("reason_in_use")
    REASON_IN_USE("reason_in_use"),
    @XmlEnumValue("status_in_use")
    STATUS_IN_USE("status_in_use"),
    @XmlEnumValue("set_in_use")
    SET_IN_USE("set_in_use"),
    @XmlEnumValue("set_not_exists")
    SET_NOT_EXISTS("set_not_exists");
    private final String value;

    ErrorReasonType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ErrorReasonType fromValue(String v) {
        for (ErrorReasonType c: ErrorReasonType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
