//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.30 at 09:31:19 PM VLAT 
//


package ru.ptkom.ecsscallrecordsback.model.CallHistoryModel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="request">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="domain" type="{}domainType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "in")
public class In {

    @XmlElement(required = true)
    protected In.Request request;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link In.Request }
     *     
     */
    public In.Request getRequest() {
        return request;
    }


    public In(String domainName, String limit, String fromDate, String toDate, String number, CallsTypeType callsType) {

        DomainType domain = new DomainType(domainName, limit, fromDate, toDate, number, callsType);
        In.Request request = new In.Request();
        request.setDomain(domain);
        this.request = request;
    }


    public In(String domainName, BigInteger limit, String fromDate, String toDate, String number, CallsTypeType callsType) {

        DomainType domain = new DomainType(domainName, limit, fromDate, toDate, number, callsType);
        In.Request request = new In.Request();
        request.setDomain(domain);
        this.request = request;
    }


    public In() {}




    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link In.Request }
     *     
     */
    public void setRequest(In.Request value) {
        this.request = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="domain" type="{}domainType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domain"
    })
    public static class Request {

        @XmlElement(required = true)
        protected DomainType domain;

        /**
         * Gets the value of the domain property.
         * 
         * @return
         *     possible object is
         *     {@link DomainType }
         *     
         */
        public DomainType getDomain() {
            return domain;
        }

        /**
         * Sets the value of the domain property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainType }
         *     
         */
        public void setDomain(DomainType value) {
            this.domain = value;
        }

    }

}
