//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.30 at 09:21:39 PM VLAT 
//


package ru.ptkom.ecsscallrecordsback.model.CallHistoryModel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inetProtocolType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="inetProtocolType">
 *   &lt;restriction base="{}unionType">
 *     &lt;enumeration value="udp"/>
 *     &lt;enumeration value="tcp"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "inetProtocolType")
@XmlEnum
public enum InetProtocolType {

    @XmlEnumValue("udp")
    UDP("udp"),
    @XmlEnumValue("tcp")
    TCP("tcp");
    private final String value;

    InetProtocolType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InetProtocolType fromValue(String v) {
        for (InetProtocolType c: InetProtocolType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
