//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.30 at 09:31:19 PM VLAT 
//


package ru.ptkom.ecsscallrecordsback.model.CallHistoryModel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ncSetInType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ncSetInType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="cluster" type="{}clusterOptionsType"/>
 *         &lt;element name="node" type="{}nodeOptionsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ncSetInType", propOrder = {
    "clusterAndNode"
})
public class NcSetInType {

    @XmlElements({
        @XmlElement(name = "cluster", required = true, type = ClusterOptionsType.class),
        @XmlElement(name = "node", required = true, type = NodeOptionsType.class)
    })
    protected List<Object> clusterAndNode;

    /**
     * Gets the value of the clusterAndNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clusterAndNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClusterAndNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClusterOptionsType }
     * {@link NodeOptionsType }
     * 
     * 
     */
    public List<Object> getClusterAndNode() {
        if (clusterAndNode == null) {
            clusterAndNode = new ArrayList<Object>();
        }
        return this.clusterAndNode;
    }

}
