//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.30 at 09:31:19 PM VLAT 
//


package ru.ptkom.ecsscallrecordsback.model.CallHistoryModel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ptkom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ptkom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link In }
     * 
     */
    public In createIn() {
        return new In();
    }

    /**
     * Create an instance of {@link Out }
     * 
     */
    public Out createOut() {
        return new Out();
    }

    /**
     * Create an instance of {@link In.Request }
     * 
     */
    public In.Request createInRequest() {
        return new In.Request();
    }

    /**
     * Create an instance of {@link Out.Response }
     * 
     */
    public Out.Response createOutResponse() {
        return new Out.Response();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link NcSetInType }
     * 
     */
    public NcSetInType createNcSetInType() {
        return new NcSetInType();
    }

    /**
     * Create an instance of {@link SystemInfoInType }
     * 
     */
    public SystemInfoInType createSystemInfoInType() {
        return new SystemInfoInType();
    }

    /**
     * Create an instance of {@link DomainCleanOutType }
     * 
     */
    public DomainCleanOutType createDomainCleanOutType() {
        return new DomainCleanOutType();
    }

    /**
     * Create an instance of {@link DomainOptionsChangeResultType }
     * 
     */
    public DomainOptionsChangeResultType createDomainOptionsChangeResultType() {
        return new DomainOptionsChangeResultType();
    }

    /**
     * Create an instance of {@link ClusterSetOutType }
     * 
     */
    public ClusterSetOutType createClusterSetOutType() {
        return new ClusterSetOutType();
    }

    /**
     * Create an instance of {@link ClusterCleanOutType }
     * 
     */
    public ClusterCleanOutType createClusterCleanOutType() {
        return new ClusterCleanOutType();
    }

    /**
     * Create an instance of {@link NsCleanOutType }
     * 
     */
    public NsCleanOutType createNsCleanOutType() {
        return new NsCleanOutType();
    }

    /**
     * Create an instance of {@link CallType }
     * 
     */
    public CallType createCallType() {
        return new CallType();
    }

    /**
     * Create an instance of {@link NcInfoInType }
     * 
     */
    public NcInfoInType createNcInfoInType() {
        return new NcInfoInType();
    }

    /**
     * Create an instance of {@link NsInfoOutType }
     * 
     */
    public NsInfoOutType createNsInfoOutType() {
        return new NsInfoOutType();
    }

    /**
     * Create an instance of {@link SystemOptionsChangeResultType }
     * 
     */
    public SystemOptionsChangeResultType createSystemOptionsChangeResultType() {
        return new SystemOptionsChangeResultType();
    }

    /**
     * Create an instance of {@link OptionsCleanType }
     * 
     */
    public OptionsCleanType createOptionsCleanType() {
        return new OptionsCleanType();
    }

    /**
     * Create an instance of {@link SystemCleanOutType }
     * 
     */
    public SystemCleanOutType createSystemCleanOutType() {
        return new SystemCleanOutType();
    }

    /**
     * Create an instance of {@link NcSetOutType }
     * 
     */
    public NcSetOutType createNcSetOutType() {
        return new NcSetOutType();
    }

    /**
     * Create an instance of {@link ClusterOptionsCleanType }
     * 
     */
    public ClusterOptionsCleanType createClusterOptionsCleanType() {
        return new ClusterOptionsCleanType();
    }

    /**
     * Create an instance of {@link NodeOptionsChangeResultType }
     * 
     */
    public NodeOptionsChangeResultType createNodeOptionsChangeResultType() {
        return new NodeOptionsChangeResultType();
    }

    /**
     * Create an instance of {@link DomainSetOutType }
     * 
     */
    public DomainSetOutType createDomainSetOutType() {
        return new DomainSetOutType();
    }

    /**
     * Create an instance of {@link NodeOptionsCleanType }
     * 
     */
    public NodeOptionsCleanType createNodeOptionsCleanType() {
        return new NodeOptionsCleanType();
    }

    /**
     * Create an instance of {@link NsSetOutType }
     * 
     */
    public NsSetOutType createNsSetOutType() {
        return new NsSetOutType();
    }

    /**
     * Create an instance of {@link NcCleanOutType }
     * 
     */
    public NcCleanOutType createNcCleanOutType() {
        return new NcCleanOutType();
    }

    /**
     * Create an instance of {@link ClusterOptionsType }
     * 
     */
    public ClusterOptionsType createClusterOptionsType() {
        return new ClusterOptionsType();
    }

    /**
     * Create an instance of {@link DomainOptionsType }
     * 
     */
    public DomainOptionsType createDomainOptionsType() {
        return new DomainOptionsType();
    }

    /**
     * Create an instance of {@link DomainInfoInType }
     * 
     */
    public DomainInfoInType createDomainInfoInType() {
        return new DomainInfoInType();
    }

    /**
     * Create an instance of {@link ClusterOptionsChangeResultType }
     * 
     */
    public ClusterOptionsChangeResultType createClusterOptionsChangeResultType() {
        return new ClusterOptionsChangeResultType();
    }

    /**
     * Create an instance of {@link ClusterCleanInType }
     * 
     */
    public ClusterCleanInType createClusterCleanInType() {
        return new ClusterCleanInType();
    }

    /**
     * Create an instance of {@link SuccessType }
     * 
     */
    public SuccessType createSuccessType() {
        return new SuccessType();
    }

    /**
     * Create an instance of {@link UnsuccessType }
     * 
     */
    public UnsuccessType createUnsuccessType() {
        return new UnsuccessType();
    }

    /**
     * Create an instance of {@link DomainInfoOutType }
     * 
     */
    public DomainInfoOutType createDomainInfoOutType() {
        return new DomainInfoOutType();
    }

    /**
     * Create an instance of {@link DomainCleanInType }
     * 
     */
    public DomainCleanInType createDomainCleanInType() {
        return new DomainCleanInType();
    }

    /**
     * Create an instance of {@link SystemSetOutType }
     * 
     */
    public SystemSetOutType createSystemSetOutType() {
        return new SystemSetOutType();
    }

    /**
     * Create an instance of {@link DomainOutType }
     * 
     */
    public DomainOutType createDomainOutType() {
        return new DomainOutType();
    }

    /**
     * Create an instance of {@link DomainType }
     * 
     */
    public DomainType createDomainType() {
        return new DomainType();
    }

    /**
     * Create an instance of {@link ClusterInfoOutType }
     * 
     */
    public ClusterInfoOutType createClusterInfoOutType() {
        return new ClusterInfoOutType();
    }

    /**
     * Create an instance of {@link NcInfoOutType }
     * 
     */
    public NcInfoOutType createNcInfoOutType() {
        return new NcInfoOutType();
    }

    /**
     * Create an instance of {@link NsInfoInType }
     * 
     */
    public NsInfoInType createNsInfoInType() {
        return new NsInfoInType();
    }

    /**
     * Create an instance of {@link DomainOptionsCleanType }
     * 
     */
    public DomainOptionsCleanType createDomainOptionsCleanType() {
        return new DomainOptionsCleanType();
    }

    /**
     * Create an instance of {@link NsCleanInType }
     * 
     */
    public NsCleanInType createNsCleanInType() {
        return new NsCleanInType();
    }

    /**
     * Create an instance of {@link NodeOptionsType }
     * 
     */
    public NodeOptionsType createNodeOptionsType() {
        return new NodeOptionsType();
    }

    /**
     * Create an instance of {@link NsSetInType }
     * 
     */
    public NsSetInType createNsSetInType() {
        return new NsSetInType();
    }

    /**
     * Create an instance of {@link SystemOptionsCleanType }
     * 
     */
    public SystemOptionsCleanType createSystemOptionsCleanType() {
        return new SystemOptionsCleanType();
    }

    /**
     * Create an instance of {@link SystemInfoOutType }
     * 
     */
    public SystemInfoOutType createSystemInfoOutType() {
        return new SystemInfoOutType();
    }

    /**
     * Create an instance of {@link ClusterSetInType }
     * 
     */
    public ClusterSetInType createClusterSetInType() {
        return new ClusterSetInType();
    }

    /**
     * Create an instance of {@link DomainSetInType }
     * 
     */
    public DomainSetInType createDomainSetInType() {
        return new DomainSetInType();
    }

    /**
     * Create an instance of {@link NcCleanInType }
     * 
     */
    public NcCleanInType createNcCleanInType() {
        return new NcCleanInType();
    }

    /**
     * Create an instance of {@link SystemSetInType }
     * 
     */
    public SystemSetInType createSystemSetInType() {
        return new SystemSetInType();
    }

    /**
     * Create an instance of {@link SystemOptionsType }
     * 
     */
    public SystemOptionsType createSystemOptionsType() {
        return new SystemOptionsType();
    }

    /**
     * Create an instance of {@link SystemCleanInType }
     * 
     */
    public SystemCleanInType createSystemCleanInType() {
        return new SystemCleanInType();
    }

    /**
     * Create an instance of {@link ClusterInfoInType }
     * 
     */
    public ClusterInfoInType createClusterInfoInType() {
        return new ClusterInfoInType();
    }

}
